@startuml
class ReadSchedule {
    <<const>> SCHEDULE_URL : string = "https://stingray-app-vgak2.ondigitalocean.app/schedules"
    + ReadSchedule()
    # <<override>> RegisterInputParams(pManager:GH_Component.GH_InputParamManager) : void
    # <<override>> RegisterOutputParams(pManager:GH_Component.GH_OutputParamManager) : void
    # <<override>> SolveInstance(DA:IGH_DataAccess) : void
}
GH_Component <|-- ReadSchedule
ReadSchedule --> "ComponentGuid" Guid
@enduml
