@startuml
class UpdateConstruction {
    + UpdateConstruction()
    # <<override>> RegisterInputParams(pManager:GH_Component.GH_InputParamManager) : void
    # <<override>> RegisterOutputParams(pManager:GH_Component.GH_OutputParamManager) : void
    # <<override>> SolveInstance(DA:IGH_DataAccess) : void
}
GH_Component <|-- UpdateConstruction
UpdateConstruction --> "ComponentGuid" Guid
@enduml
