@startuml
class ExportR {
    + ExportR()
    # <<override>> RegisterInputParams(pManager:GH_Component.GH_InputParamManager) : void
    # <<override>> RegisterOutputParams(pManager:GH_Component.GH_OutputParamManager) : void
    # <<override>> SolveInstance(DA:IGH_DataAccess) : void
}
GH_Component <|-- ExportR
ExportR --> "ComponentGuid" Guid
@enduml
